### ISSUE TITLE
what is the version of .NET that is supported in Garden-windows

### ISSUE THREAD

**Issue by VenkateshSrini** [cloudfoundry/garden-windows#12]
Hi,
Can you please let us know what is the version of .NET that is supported in garden-windows.

Thanks and regards
Venkatesh

**Comment by sbenario** [comment]
Garden-Windows is agnostic of the version of .NET that is installed on your Windows Server. It will support whatever is installed on the cell (eg. 3.5, 4.5, 4.6, etc)

**Comment by VenkateshSrini** [comment]
How to install .net 4.6 in cell. Can you point me to some steps

**Comment by sbenario** [comment]
Microsoft has some good instructions:  https://msdn.microsoft.com/en-us/library/5a4x27ek(v=vs.110).aspx
