### ISSUE TITLE
System.Exception: Protocol 3 is unknown

### ISSUE THREAD

**Issue by frodenas** [cloudfoundry/garden-windows#15]
A customer has been unable to push Windows apps lately to their CF environment. It took us some time to discover what was really happening, but after searching the windows cell event log for error messages we saw this:

```json
{
  "source": "Containerizer",
  "timestamp": "1489059556.272680000",
  "message": "unhandled exception",
  "data": {
    "exception": {
      "ClassName": "System.Exception",
      "Message": "Protocol 3 is unknown",
      "Data": null,
      "InnerException": null,
      "HelpURL": null,
      "StackTraceString": " at IronFrame.Utilities.FirewallManager.CreateFirewallRuleForProtocol(String windowsUserName, Protocol proto, FirewallRuleSpec firewallRuleSpec)\r\n at IronFrame.Container.CreateOutboundFirewallRule(FirewallRuleSpec firewallRuleSpec)\r\n at Containerizer.Controllers.NetController.NetOut(String handle, FirewallRuleSpec netOutRequest)\r\n at lambda_method(Closure , Object , Object[] )\r\n at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()",
      "RemoteStackTraceString": null,
      "RemoteStackIndex": 0,
      "ExceptionMethod": "8\nCreateFirewallRuleForProtocol\nIronFrame, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null\nIronFrame.Utilities.FirewallManager\nVoid CreateFirewallRuleForProtocol(System.String, IronFrame.Protocol, IronFrame.FirewallRuleSpec)",
      "HResult": -2146233088,
      "Source": "IronFrame",
      "WatsonBuckets": null
    },
    "method": "POST",
    "uri": "http://localhost:1788/api/containers/6a059603-6e4f-452f-a5c8-16733524491a/net/out",
    "route_template": "api/containers/{handle}/net/out",
    "arguments": {
      "handle": "6a059603-6e4f-452f-a5c8-16733524491a",
      "net_out_request": {
        "protocol": 3,
        "networks": [
          {
            "start": "0.0.0.0",
            "end": "255.255.255.255"
          }
        ],
        "ports": null,
        "remote_addresses": "0.0.0.0-255.255.255.255",
        "remote_ports": "*"
      }
    }
  },
  "log_level": 2
}
```
It seems an admin user was doing some tests and created a CF application security group to enabe `icmp` protocol:

```json
[
  {
    "code": 1,
    "destination": "0.0.0.0/0",
    "protocol": "icmp",
    "type": 0
  }
]
```

Although `icmp` is a [valid protocol](https://docs.cloudfoundry.org/adminguide/app-sec-groups.html#creating-groups) for CF application security groups, seems that the `FirewallManager` [does NOT accept](https://github.com/cloudfoundry/IronFrame/blob/c5e051b9baddf8dabd87904743f9c7c25c420424/IronFrame/Utilities/FirewallManager.cs#L122) it.

So:
1) Can you please add support for the `icmp` protocol?
2) If `icmp` protocol cannot be supported, can garden drop that firewall rule before creating the container (and maybe emit a warning message)?

For reference, the customer is using [diego-windows-release v0.474](https://github.com/cloudfoundry/diego-windows-release/tree/v0.474) & [garden-windows-release v0.199](https://github.com/cloudfoundry/garden-windows-release/tree/v0.199).

**Comment by sunjayBhatia** [comment]
@frodenas have you been able to get around this?

**Comment by frodenas** [comment]
@sunjayBhatia No, the only fix was to delete the ICMP rule.

**Comment by sunjayBhatia** [comment]
@frodenas as per the [api differences doc](https://github.com/cloudfoundry/garden-windows/blob/7f2ac49420b95137b44a0a2fe292eb3265bf5f3b/api-differences.md) which is not very discoverable tbh, you can't configure ICMP rules on your Windows cells at all

**Comment by frodenas** [comment]
@sunjayBhatia well, the problem is that when you create a security group via the CF CLI, there's no way to specify the target cells (or the stack, or whatever, ...). I don't believe a lot of users are using ICMP rules, but if they do and they also use Windows cells, their won't be able to push Windows apps anymore.

**Comment by sunjayBhatia** [comment]
@frodenas Is it a reasonable workaround to deploy your Windows apps into a CF space that does not have the ICMP rule bound to it? Apps in other spaces could still have the rule if required. Let us know if this is an ok workaround while we talk about solving this issue.

@crawsible @awmartin

**Comment by frodenas** [comment]
@sunjayBhatia We removed that ICMP rule (it was useless), so we are not facing this issue anymore (until someone adds that rule again  :grin:)

**Comment by sunjayBhatia** [comment]
@frodenas would you be ok with closing this? i guess we will bring this back if theres more demand for ICMP rules on garden-windows

**Comment by frodenas** [comment]
@sunjayBhatia I'm not convinced of closing it. It's not about supporting ICMP, it's about apps failing to start if someone adds (maybe by mistake) an ICMP rule. Can we ask the garden-windows to drop that rule? Or maybe, can we document it somewhere (may be in the security groups docs) that if you add an ICMP rule your Windows apps will NOT start?

**Comment by tcdowney** [comment]
For what it's worth, we (CAPI team) started seeing the wats (windows-acceptance-tests) fail in our pipelines with the error `ERR Failed to create container` when pushing windows apps.  We had to dig into the bosh logs for our windows-cell VMs and were only able to find that they were failing due to the `"Protocol 3 is unknown"` error.

Without this Github Issue we wouldn't have been able to figure out that it was our testing around security-groups that caused the failures.  So at the very least a better error message would be valuable.

**Comment by jvshahid** [comment]
@sunjayBhatia it looks like the right thing to do here is to modify garden-windows to skip/ignore icmp security groups

**Comment by sunjayBhatia** [comment]
Yeah @jvshahid I think @crawsible and I should reconsider doing this

**Comment by crawsible** [comment]
We've added a story for ignoring ICMP rules to our tracker [here](https://www.pivotaltracker.com/story/show/141403535). We'll ping here again when it makes it into a release.

**Comment by crawsible** [comment]
Re-opening until we cut a release.

**Comment by crawsible** [comment]
@frodenas @jvshahid @tcdowney [garden-windows-bosh-release v0.7.0](https://github.com/cloudfoundry-incubator/garden-windows-bosh-release/releases/tag/v0.7.0) includes the fix to ignore ICMP NetOutRules.
