### ISSUE TITLE
cf push to Windows cell failed

### ISSUE THREAD

**Issue by varun7447** [cloudfoundry/garden-windows#19]
Trying to push a .Net 4.6 application to Cloud foundry. I see this error message. Am i missing anything below is my 

`cf push "${CF_APP_NAME}" -s windows2012R2`

   2017-11-10T00:38:18.22+0000 [CELL/0] OUT Creating container
   2017-11-10T00:38:18.34+0000 [API/0] OUT Process has crashed with type: "web"
   2017-11-10T00:38:18.34+0000 [API/0] OUT App instance exited with guid 5ac3cf42-f5dd-429f-a8c8-6bb05f1a862d payload: {"instance"=>"72e48479-b61c-48ef-4872-cd97", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"Copying into the container failed", "crash_count"=>1, "crash_timestamp"=>1510274298289640830, "version"=>"d037ca23-b75e-444f-aa2c-eea64784c648"}
   2017-11-10T00:38:18.35+0000 [CELL/0] ERR Failed to create container

**Comment by awmartin** [comment]
@varun7447 Are you using cf-deployment? If so, what version and what stemcell version?

**Comment by varun7447** [comment]
Yes cf-deployment
Cloud Foundry Version: cf version 6.32.0+0191c33d9.2017-09-26
Stemcell Version: 1200.7

**Comment by awmartin** [comment]
Thanks, but that's the version of the CF CLI, but what [version of cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases)? That will tell us the versions of the releases.

**Comment by varun7447** [comment]
Just not able to find the version. It has been 3 weeks.

**Comment by awmartin** [comment]
What IaaS? If it's AWS, there's a known issue with the current stemcells where the root partition isn't sized greater than 30GB, even if you specify something larger in your manifest. We're intending to ship a fix for that next week.

**Comment by varun7447** [comment]
Ok, I cleanup all my apps and tried still same message. Is there a way to force cleanup ? Cache cleanup?

**Comment by awmartin** [comment]
Can you get into the box and see what's taking up the space? It could be a number of things, like the Diego executor cache or the Windows component store, etc.

**Comment by varun7447** [comment]
For now i added one more windows cell. I forgot to create a Windows JumpBox to RDP to the windows cell. Is there a recommended way of creating a windows Jump box for accessing the Windows cells? Is there an automatic way to deploy a Windows Jumpbox like Linux jump box ?

**Comment by varun7447** [comment]
Is the fix for "What IaaS? If it's AWS, there's a known issue with the current stemcells where the root partition isn't sized greater than 30GB, even if you specify something larger in your manifest. We're intending to ship a fix for that next week." is available ??

**Comment by awmartin** [comment]
The story with the fix was completed last week: https://www.pivotaltracker.com/story/show/152013410
It will be available in the 1200.10 stemcell, hopefully this week.

**Comment by varun7447** [comment]
Thanks Martin. I will try this. I am closing this issue for now.
